export const EVENTS_TABLE = 'biztechEvents';
export const MEMBERSHIPS2021_TABLE = 'biztechMemberships2021';
// export const MEMBERSHIPS2022_TABLE = 'biztechMemberships2022';
export const PRIZES_TABLE = 'biztechPrizes';
export const STICKERS_TABLE = 'biztechStickers';
export const TRANSACTIONS_TABLE = 'biztechTransactions';
export const USERS_TABLE = 'biztechUsers';
export const USER_INVITE_CODES_TABLE = 'inviteCodes';
export const USER_REGISTRATIONS_TABLE = 'biztechRegistrations';
