module.exports = {
  INTEGRATION_TEST_USER_ID: -40,
  INTEGRATION_TEST_PERSISTENT_USER_ID: -60,
  INTEGRATION_TEST_NON_EXISTANT_USER_ID: -598765230,
  INTEGRATION_TEST_EVENT_ID: '__INTEGRATION_TEST_EVENT_POST',
  INTEGRATION_TEST_PERSISTENT_EVENT_ID: '__INTEGRATION_TEST_EVENT',
  INTEGRATION_TEST_PERSISTENT_EVENT_ID_2: '__INTEGRATION_TEST_EVENT_2',
  INTEGRATION_TEST_NON_EXISTANT_EVENT_ID: 'someRandomEventThatDoesNotExist123',
};
