'use strict';
const AWSMock = require('aws-sdk-mock');

// tests for eventCreate
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('eventCreate', '/handlers/event.js', 'create');
const { EVENTS_TABLE } = require('../constants/tables');

const eventPayload = {
  id: 'localTestEvent',
  ename: 'Local Test Event',
  description: 'Local test event description',
  startDate: '20200607T000000-0400',
  endDate: '20200607T000000-0400',
  capac: 100,
  facebookUrl: 'https://www.facebook.com/BizTechUBC/',
  imageUrl: 'https://www.facebook.com/BizTechUBC/',
  elocation: 'https://i.picsum.photos/id/320/200/300.jpg',
  longitude: -120.00,
  latitude: 78.00,
  createdAt: '20200607T000000-0400',
  updatedAt: '20200607T000000-0400'
};

describe('eventCreate', () => {

  let createdEventIds = [];

  before(() => {

    AWSMock.mock('DynamoDB.DocumentClient', 'get', (params, callback) => {

      const { id } = params.Key;

      if(params.TableName.includes(EVENTS_TABLE)) {

        // if id found
        if(createdEventIds.includes(id)) callback(null, { Item: eventPayload });
        // if id not found
        else callback(null, { Item: null });

      }

    });

    AWSMock.mock('DynamoDB.DocumentClient', 'put', (params, callback) => {

      if(params.Item.id && createdEventIds.includes(params.Item.id)) callback(new Error('event already exists!'));
      else {

        createdEventIds.push(params.Item.id);
        callback(null, 'successfully put item in database');

      }

    });

  });
  after(() => {

    AWSMock.restore('DynamoDB.DocumentClient');

  });

  it('return 406 for trying to create an event with no id', async () => {

    const invalidPayload = {
      ...eventPayload
    };
    delete invalidPayload.id;

    const response = await wrapped.run({ body: JSON.stringify(invalidPayload) });
    expect(response.statusCode).to.be.equal(406);

  });

  it('return 406 for trying to create an event with invalid capac', async () => {

    const invalidPayload = {
      ...eventPayload
    };
    delete invalidPayload.capac;

    const response = await wrapped.run({ body: JSON.stringify(invalidPayload) });
    expect(response.statusCode).to.be.equal(406);

  });

  it('return 201 for successfully creating an event', async () => {

    const payload = {
      ...eventPayload,
    };

    const response = await wrapped.run({ body: JSON.stringify(payload) });
    expect(response.statusCode).to.be.equal(201);

  });

  it('return 409 for trying to create an event with the same id', async () => {

    const payload = {
      ...eventPayload,
    };

    const response = await wrapped.run({ body: JSON.stringify(payload) });
    expect(response.statusCode).to.be.equal(409);

  });

});
