'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('hello', '/handlers/default.js', 'hello');
const AWS = require('aws-sdk');
 

describe('hello', () => {
  before((done) => {
    done();
  });

  it('hello test', async () => {
    const response = await wrapped.run({});
    const body = JSON.parse(response.body);
    expect(response).to.not.be.empty;
    expect(body.message).to.equal("Yeet!");
    expect(response.statusCode).to.equal(200);

    const options = {
      region: "us-west-2"
    }
    const lambda = new AWS.Lambda(options);
    let params = {
      FunctionName: "biztechApp-dev-hello",
    }
    lambda.invoke(params, function(err, data) {
      if (err) console.log(err);
      else console.log(data);
      console.log("ASDSADASDASDASD");
    });
  });
});
