'use strict';

// tests for registrationPost
// Generated by serverless-mocha-plugin

const AWSMock = require('aws-sdk-mock');
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('registrationPost', '/handlers/registration.js', 'post');
const { EVENTS_TABLE, USERS_TABLE, USER_REGISTRATIONS_TABLE } = require('../constants/tables');

const userResponse = {
  id: 12200034,
  fname: 'user',
  lname: 'man',
  faculty: 'Science',
  email: 'test@test.com'
};

const eventResponse = {
  'id': 'event',
  'year': 2020,
  'capac': 2,
  'createdAt': 1581227718674,
  'description':	'I am a description',
  'elocation': 'UBC',
  'ename': 'Existing Event',
  'startDate': '2020-02-09T05:55:11.131Z',
  'endDate':	'2020-02-09T05:55:11.131Z',
  'imageUrl':	'https://i.picsum.photos/id/236/700/400.jpg',
  'updatedAt': 1581227718674
};

const registrationsResponse = [
  {
    id: 12345677,
    ['eventID;year']: 'event;2020',
    updatedAt: 1600669844493,
    registrationStatus: 'registered'
  },
  {
    id: 12345678,
    ['eventID;year']: 'event;2020',
    updatedAt: 1600669844493,
    registrationStatus: 'registered'
  }
];

describe('registrationPost', () => {

  before(() => {

    AWSMock.mock('DynamoDB.DocumentClient', 'get', (params, callback) => {

      if(params.TableName.includes(EVENTS_TABLE)) {

        if(params.Key.id === 'event' && params.Key.year === 2020) callback(null, { Item: eventResponse });
        else callback(null, { Item: null });

      }
      else if(params.TableName.includes(USERS_TABLE)) {

        if(params.Key.id === 12200034) callback(null, { Item: userResponse });
        else if(params.Key.id === 12345678) callback(null, { Item: { ...userResponse, id: 12345678 } });
        else callback(null, { Item: null });

      }
      return null;

    });

    AWSMock.mock('DynamoDB.DocumentClient', 'scan', (params, callback) => {

      if(params.TableName.includes(USER_REGISTRATIONS_TABLE)) {

        callback(null, { Items: registrationsResponse });
        return null;

      }

    });

    AWSMock.mock('DynamoDB.DocumentClient', 'update', (params, callback) => {

      // for POST
      // throw error if already exists (only check for 12345678)
      if(params.Key.id === 12345678 && params.Key['eventID;year'] === 'event;2020') callback({ code: 'ConditionalCheckFailedException' });
      else callback(null, 'Created!');

      return null;

    });

  });

  after(() => {

    AWSMock.restore('DynamoDB.DocumentClient');

  });

  it('should return 406 when id is not given ', async () => {

    const response = await wrapped.run({
      body: JSON.stringify({
        ['eventID;year']: 'event;2020',
      })
    });
    expect(response.statusCode).to.be.equal(406);

  });

  it('should return 406 when no eventID;year is provided', async () => {

    const response = await wrapped.run({
      body: JSON.stringify({
        id: 12200034,
        registrationStatus: 'registered'
      })
    });
    expect(response.statusCode).to.be.equal(406);

  });

  it('should return 406 when no registrationStatus is provided', async () => {

    const response = await wrapped.run({
      body: JSON.stringify({
        id: 12200034,
        ['eventID;year']: 'event;2020',
      })
    });
    expect(response.statusCode).to.be.equal(406);

  });

  it('should return 404 when unknown event id is provided', async () => {

    const response = await wrapped.run({
      body: JSON.stringify({
        id: 12200034,
        ['eventID;year']: 'unknownEvent;2020',
        registrationStatus: 'registered'
      })
    });
    expect(response.statusCode).to.be.equal(404);

  });

  it('should return 404 when unknown user id is provided', async () => {

    const response = await wrapped.run({
      body: JSON.stringify({
        id: 1220003424657,
        ['eventID;year']: 'event;2020',
        registrationStatus: 'registered'
      })
    });
    expect(response.statusCode).to.be.equal(404);

  });

  it('should return 201 for successful creation of registration as waitlist', async () => {

    const response = await wrapped.run({
      body: JSON.stringify({
        id: 12200034,
        ['eventID;year']: 'event;2020',
        registrationStatus: 'waitlist'
      }),
    });

    const body = JSON.parse(response.body);
    expect(response.statusCode).to.equal(201);
    expect(body.registrationStatus).to.equal('waitlist');

  });

  it('should return 201 for successful creation of registration with maximum capac', async () => {

    const response = await wrapped.run({
      body: JSON.stringify({
        id: 12200034,
        ['eventID;year']: 'event;2020',
        registrationStatus: 'registered'
      }),
    });

    const body = JSON.parse(response.body);
    expect(response.statusCode).to.equal(201);
    expect(body.registrationStatus).to.equal('waitlist');

  });

  it('should return 409 for trying to create duplicate registration entry', async () => {

    const response = await wrapped.run({
      body: JSON.stringify({
        id: 12345678,
        ['eventID;year']: 'event;2020',
        registrationStatus: 'registered'
      }),
    });
    expect(response.statusCode).to.equal(409);

  });

});
