'use strict';
const AWSMock = require('aws-sdk-mock');

// tests for transactionGetAll
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('transactionGetAll', '/handlers/transaction.js', 'getAll');

const getTransactionsResponse = require('./data/transactions.json');

describe('transactionGetAll', () => {

  before(() => {

    AWSMock.mock('DynamoDB.DocumentClient', 'scan', (params, callback) => {
        callback(null, getTransactionsResponse);
    });
    
  });

  after(() => {

    AWSMock.restore('DynamoDB.DocumentClient');

  });

  it('return 200 response for getting all transactions', async () => {

    const response = await wrapped.run();
    expect(response.statusCode).to.be.equal(200);

    const body = JSON.parse(response.body);
    expect(body).to.have.length(3);

    const event = body[0];
    expect(event).to.have.property('id');
    expect(event).to.have.property('userId');
    expect(event).to.have.property('reason');
    expect(event).to.have.property('credits');
    
  });

});
