'use strict';

// tests for userGet
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
const AWS = require('aws-sdk-mock');
let wrapped = mochaPlugin.getWrapper('userGet', '/handlers/user.js', 'get');

// If want to invoke mocha instead of sls invoke
// let wrapped = mochaPlugin.getWrapper('userGet', '../../../handlers/user.js', 'get');

describe('userGet', () => {
  before((done) => {
    done();
  });

  it('successfully get user', async () => {
    AWS.mock('DynamoDB.DocumentClient', 'get', function (params, callback){
      if (params.Key.id == 332332) {
        Promise.resolve(
          callback(null, {
            Item: 'not null user'
          } 
        ));
      }
    });
    const response = await wrapped.run({
      pathParameters: {
        id: '332332'
      }
    });
    expect(response).to.not.be.empty;
    expect(response.statusCode).to.equal(200);
    AWS.restore('DynamoDB.DocumentClient');
  });
});
