service: biztechApi-transactions
tenant: ianmh
app: biztechapp

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager
  - serverless-bundle
  - serverless-prune-plugin

provider:
  name: aws
  stage: ${file(../../serverless.common.yml):provider.stage}
  runtime: ${file(../../serverless.common.yml):provider.runtime}
  region: ${file(../../serverless.common.yml):provider.region}
  cfLogs: true
  environment:
    ENVIRONMENT: ${file(../../config.${self:provider.stage}.json):ENVIRONMENT}
  
  apiGateway:
    restApiId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechUsers${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechTransactions${self:provider.environment.ENVIRONMENT}"


custom: ${file(../../serverless.common.yml):custom}

functions:
  transactionGetAll:
    handler: handler.getAll
    events:
      - http:
          path: transactions/
          method: get
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp
  transactionCreate:
    handler: handler.create
    events:
      - http:
          path: transactions/
          method: post
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp

