language: node_js
node_js:
- node
notifications:
  email: false
install:
- npm install -g serverless
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: "Integration Tests"
      script: sls test
    - stage: "Deploy to Staging"
      script: sls deploy
    - stage: "Deploy to Production"
      script: sls deploy
stages:
  - "Integration Tests"
  - name: "Deploy to Staging"
    if: branch = dev
    if: branch = master