language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm install -g serverless
- sls config credentials --provider aws -key AWS_ACCESS_KEY_ID -s AWS_SECRET_ACCESS_KEY 
- sls deploy
env:
  global:
  - secure: MCU8KbHfu8pI7UjtCDVjqwNHrN1b0Yq2LRYkTZtwd/4KMn7oFDDwCHed5PBsQUQqlYz2Y8JHjSgTQ9BnE/3c+K6Phtd+fJcMdkB+eRNwI21RVsU8KtZVB7FRAY4pvH4Iheo5HvCwGkFbhHY8BvtH1vNcVF4gmXPxJ9IzmpxZBscOOfw3dTyEr6kG+yQxQkLgeaNh1TU7IzxLvg6AL0N4vC0QhvURol+qYxP8SXmKpJhcD5JgSOnjZXYl6R8YPjGFA1XjzvY/P5kBfDSlYuI8jxYgKEVpzdljHuR7EtwCuFrK29gdhIoUS70KyVjEOjbTHKgj6zsTwgQcjcUguqKiOufNWJ1Q7xXq/29wgpq74jssJd4jgIPmgIZghzIZ6MFAdYT9EcRH/GC3rjlJ24R3JHdGcGh7zjdx0CL6EvgplH+d1WA1EOPuEJlQvG+QBkG0P4Kffv0/fGvur4sTIkzJ/Bc/OToZpxxf6qj4oD4ckcOcBBABjEJtLDIrwDZ8CRZKpx0eHwsFFiNYc6mp/wsVSvJStxUPspVaPjlfYg5lIJ7CTJsF60MGmkafDJkGWTzGD4EYASFqsrQsP//D3Nok9lb2CquIRG6qto4IPOAxePsa+OPPQgUfTEawAmD8yy3R3PC955uUsO1kCEHDILJ+6iyMW8qLMdvxncpM+xHOrN0=
  - secure: cS0TTLaFGqlc/ekyNzwmX05m6iIt8ZerHemJAovtLpo783j9AHSJ8YrPzEv5xbEht1OtC2sx/hEUYhK9/kWu78IMRxw3X50oYNyOyCp+5kQ9QrzPYK7++91qjDsnrCxYDIZ1cY2D0zFbfC/A8fjblagywiHfCVd3ZgpjIYag50oXenWnQtjw2Sq4zNmQPO2upsk7rC71UzPep9b2M2vYE7T+NVuyi/66oscAqmSeA8FQfJB8g2St5L2kZv6YeJOhn4SfaSTeWcRGJlwDRGmHQckBtnwOm5M6KqvG4lvF/2ASDGJd2wfbTu0nXgfVRGNDNTpoTYFA2totUUZpJxdBD52q1vdbEzGWmm1RsmZ+SZHn9omsHIvI4B/DMzG2dOCkLAsTL5YutA3Rxv+Snf+OYgmqpCkLYvwCAtYiqrsdFLt0GVYKsbWVTaG9zfldTTnXT3XmcF8daOstlr0blG30IT3Ci7pq9ERUy8LsAfwRTG6xLv9YgySZyJuq6u+Mlqeg6X3ON/yNdHg0dEk8XfdkUlg0tJkKJiqSHKhh8K3gI79mC/XBAEt9GOo8YrjCMncgHIa7VtnwUq760oAy/WUznbC7hvrfzdC8QTVlHWSxPCFfae0L/B6HUJQbfNHN7EPSlecDHmOUdxdwu5AsxAGfbvch7PQv6vc3aWX/diXIbws=
