language: node_js
node_js:
- node
notifications:
  email: false
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: "Deploy and run integration tests"
      script:
        - sls deploy
        - sls invoke test
        - sls test
    - stage: "Deploy to Staging"
      script: sls deploy --stage staging --conceal
    - stage: "Deploy to Production"
      script: sls deploy --stage prod --conceal
stages:
  - name: "Deploy and run integration tests"
  - name: "Deploy to Staging"
    if: (branch = master) AND (type = push)
  - name: "Deploy to Production"
    if: tag IS present
