language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm install -g serverless
- sls config credentials --provider aws -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -o
- sls test
env:
  global:
  - secure: O9bbU7E3sFyOk8rqBAdVpjIjrtKU7PgddIrSumaJd2I1cAiou7yof6IpFU4P1T+WhMATKF9swAI4p1PeCmo81oH++V7KLXxv6wZtTD6Rcq2rkniIa55QM5vQ7wgx6CEnqjGbSzS4KNXpL5PjLmLgpEokDG+cdJa1BQK1BzNRyFBgHtbMajw6u/s5MNyIqqRKRIgEF1c6CQsi3fsVbNa+tZIAwXCHvW73KeGswr06sgm1XJMaBZFwAoz7jkVS/RIc73Kz2R7wushKaKZKnJ3/4mAfi+iD/rwN1KquROk2SoRFziG6XAQh0zUDZrbXFm8s0rzyHq0MeRh13GWHC3NXGQDgYqUxzb6S8xWBE0sKra6lAB3spuJnBHNrnsx+SaQbiGVG2wlhBeQ9Ghi8dFslgJwg/4/ra9QqWgKb4SXumzJI/8CSPAYSji5WOp0KRqjTmdmPFKFqlEylm7MPYfg54OzXlDS8s/YTPZwTkAphQRUCvSCCSu229N/Br6x6jd7FTB+nSvygisTabzngm5WFi1RtJNW95bX24jjPjgo00nsqu83kjIodISEKxMEqfAvk2gppP0CoiEvzbGeg0UDKDcPhfyZ7TspsWm74KuabFWi3o66goo7kgWoCmL3bK9ZP9cSA/UVBoWXgnAd7v7d512kSBeNHw0u4QgMGdatK32A=
  - secure: cosEzWlUIZNqybqj460YWvVwXjJrXCkj+M1u5wtR4MiiiWNikYd/Vre6WjKOblrkdDhsg1gTIXcSQHfKmi6qLvqpt7WXzTfH80byR217rik34lM4uv2O1CYmQtuQXCq5yx5brzKFNxrIuM1WSvFCP9Tg9OVeOnT0PmdL0diFZyv5e3EZLfu08XRUYujfdAhUBW1FQ4dNutEYQoyXMKhJ9Sjmm7cL0e7CIIJAQy0jY4o6My4eckb9GSEcFYXq2rVn6/Md3QAKjBbk6odZvoe6pOL0T973CHNMjd0O2J6q68tgABopyDpsNUTnrUsw4JMF4tYf4ndYHHxDQJJR0Iis8C8M7sGy5c1RNkVOcSbDjRSYWLbXLv39IzyIsOzyL+V82mjcAGgNA4FDUbBgX1W6acNVD5njGlYbBCXy4sD68wyfVy9ZFm1Jn4OLxmlv6zIreFIEfjT5k6NwkU9SWj438oFLD0ujZN5VV2955S0Bat8dDOK9yLwDt9Ojzm6y49KV4vua3bDcoYMIeEd9kC7qXOMxyEoWEqHSEuVawSQXpdY7AQccxhpIHD7ci0WI8iaFMGMdRN56J8JxWIRvQalZTY0V4Rx3D+0cN9UpnTvUFFsnRm0k2S5nbD7RpAahzj0CdS4bdqc6oUiEianG9VAgUUtKedjwojQzpYOVr/TuVrA=
