language: node_js
node_js:
- node
env:
- ARNCODE = $ARN_CODE
cache:
  directories:
  - node_modules
script:
- npm install -g serverless
- sls config credentials --provider aws -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -o
- sls test
env:
  global:
  - secure: KjOfY1dMK2n3PtCph+A6bfdNu89B0KAi8IgF48KsYzjz5plnajusrwqx73VH1ISiSkYzYuNU4Ws9Nj6P9lpYBfSJUk9mHoR6df9XtL1pDhJw76Zo29ywnjQKiZhl0SE0PjOkX7I+y2Nhc8FEDY19HgDMyKymWTCz9B0LauyMSrE6h6j+aURMswuoQsKfHF+YEW5y4+3oYii7DPkgyvHjeJ+5H1y+Ch1pVL9fh7f8ZVSLIkDRSRqQi8MNmlhCX/CtNBsyT5HdgBbuPdizNkfGsCpYlvjpdcq+uRazU5H1006VZRSRTzFkinU61hDpykyaMQ95gP3IKwepWZ3wbF2S3f+BfMqY+RveRMcT+HNRrevZCr/ynGI7pZlpcUxoFxVES/ZIC0AzpvFSGL7ufvD2pmZUE1SoaTKMP9i+lpjXNiua29I4Ez0GLYXUCfnT/l9M6jGbp3+WALPsrni0A7CyUlW+N8Xt7q3Y7StWp0+bXYjGLMayfiENdyVFHpw4IM2+GrVSBP1ycK8cNG36O/6vJZa5f33Q8buLUVDmgir/EnVx+PhdjBkP3titk5JJ6LsNZv+QWm14vSHAkgXZ1JD438jSpKdoyeA8OwkXHwg4bClKSRog0VDO2STQ1K28QqgB97zMS7I6VoN++j8BsBCkPWwsSrjixDHpu55A4O7kmLI=
  - secure: Xoe8NSwnTfTeCC7gNCuBVPr4Kp9KIzJTtk9NEP9w8txDS6O6w6Kqg7mWNfvLdJNWDDqgRvcOmv91Q+QtScE2ZlQhSfqwdI22zvkQwAWFTNXeoEcA2jV/4sPP5gefSXDKY66RHvTvEPrdeCE/nsozH9jH7ZFjgmjBZCsio+eZ9R7L0EYv93TFkGx0RpUo1/yxqyI/iqFIbtolTHWvJ3vuOKItZ1K8rmk74wZsopuXz0IISDNyfYAHUhBQ2yMx1RZVvIQxfiAkRsz3HbbKQuYQ5ZJHUZu/EHJVkdJd57CUutlgs3HgwENERKrMpNuTab7TulhVqB131PK7c7II/5SRzoe57jrZ7wHWcLg/W5vEbinMQRgShQs4vqLg2JQMvGZMgakSSd0RJ8XzbWdWxgoxG7iY1UIwBQnozrweS60tL+qYPBca8F4IfUeU9KyXibpaLxQUvm26AnfCKZVkVw28Jfq1PSKayUmJwxxXWGmGgkCccAVEaUZkrzBU1lKt3Jfgw6Ai//jgglVUPVZ2DY6h+UKrtaqYsBIeb+kwSbwTBtg9sZqfYFQZH+Pxqb/Xqa2npSNbZvJh6tGWJMNvwTiq3uMDFskCejlukfeSF4aIGKlvKEjaSu6jRYnXWGzcQc86c5dhXfngy0ihrcRtTojBWWvW3UxdTRQaFjIMYxBiPOQ=
