service: biztechApi-stickers
app: biztechapp

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-domain-manager
  - serverless-apigateway-plugin
  - serverless-bundle
  - serverless-prune-plugin
  - serverless-mocha-plugin

provider:
  name: aws
  stage: ${file(../../serverless.common.yml):provider.stage}
  runtime: ${file(../../serverless.common.yml):provider.runtime}
  region: ${file(../../serverless.common.yml):provider.region}
  websocketsApiName: ${self:service}
  websocketsApiRouteSelectionExpression: $request.body.action
  websocketsDescription: user voting and stickers
  environment:
    ENVIRONMENT: ${file(../../config.${self:provider.stage}.json):ENVIRONMENT}
    NODE_ENV: ${env:NODE_ENV}
  apiGateway:
    restApiId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/bizSockets${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/bizSockets${self:provider.environment.ENVIRONMENT}/index/*"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/bizStickers${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/bizStickers${self:provider.environment.ENVIRONMENT}/index/*"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/bizScores${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/bizScores${self:provider.environment.ENVIRONMENT}/index/*"

custom: ${file(../../serverless.common.yml):custom}

build:
  esbuild: false

functions:
  connectHandler:
    handler: handler.connectHandler
    events:
      - websocket:
          route: $connect
  disconnectHandler:
    handler: handler.disconnectHandler
    events:
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: handler.defaultHandler
    events:
      - websocket: $default
  adminHandler:
    handler: handler.adminHandler
    events:
      - websocket:
          route: admin
  stickerHandler:
    handler: handler.stickerHandler
    events:
      - websocket:
          route: sticker
  scoreHandler:
    handler: handler.scoreHandler
    events:
      - websocket:
          route: score
  syncHandler:
    handler: handler.syncHandler
    events:
      - websocket:
          route: sync
  scoresGetAll:
    handler: handler.getScores
    events:
      - http:
          path: scores/
          method: get
          cors: true
  scoresGetRoom:
    handler: handler.getScoresRoom
    events:
      - http:
          path: scores/{roomID}
          request:
            path:
              roomID: true
          method: get
          cors: true
  scoresGetTeam:
    handler: handler.getScoresTeam
    events:
      - http:
          path: scores/team/{teamName}
          request:
            path:
              teamName: true
          method: get
          cors: true
  stickersGetAll:
    handler: handler.getStickers
    events:
      - http:
          path: stickers/
          method: get
          cors: true
  stickersGetRoom:
    handler: handler.getStickersRoom
    events:
      - http:
          path: stickers/{roomID}
          request:
            path:
              roomID: true
          method: get
          cors: true
  stickersGetTeam:
    handler: handler.getStickersTeam
    events:
      - http:
          path: stickers/team/{teamName}
          request:
            path:
              teamName: true
          method: get
          cors: true
