service: biztechApi-qr
tenant: ianmh
app: biztechapp

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-domain-manager
  - serverless-bundle
  - serverless-prune-plugin
  - serverless-mocha-plugin

provider:
  name: aws
  stage: ${file(../../serverless.common.yml):provider.stage}
  runtime: ${file(../../serverless.common.yml):provider.runtime}
  region: ${file(../../serverless.common.yml):provider.region}
  cfLogs: true
  environment:
    ENVIRONMENT: ${file(../../config.${self:provider.stage}.json):ENVIRONMENT}
    NODE_ENV: ${env:NODE_ENV}
  apiGateway:
    restApiId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechRegistrations${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechQRs${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechTeams${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechUsers${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechEvents${self:provider.environment.ENVIRONMENT}"

custom: ${file(../../serverless.common.yml):custom}

functions:
  qrScan:
    handler: handler.post
    events:
      - http:
          path: qrscan/
          method: post
          cors: true
  qrGetAll:
    handler: handler.get
    events:
      - http:
          path: qr/
          method: get
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp
  qrGetOne:
    handler: handler.getOne
    events:
      - http:
          path: qr/{id}/{eventID}/{year}
          method: get
          request:
            path:
              id: true
              eventID: true
              year: true
          cors: true
  qrCreate:
    handler: handler.create
    events:
      - http:
          path: qr/
          method: post
          cors: true
  qrUpdate:
    handler: handler.update
    events:
      - http:
          path: qr/{id}/{eventID}/{year}
          method: patch
          request:
            path:
              id: true
              eventID: true
              year: true
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp
qrDelete:
    handler: handler.del
    events:
      - http:
          path: qr/{id}/{eventID}/{year}
          method: delete
          request:
            path:
              id: true
              eventID: true
              year: true
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp


