'use strict';
import AWSMock from 'aws-sdk-mock';

// tests for stickerUpdate
// Generated by serverless-mocha-plugin

import mochaPlugin from 'serverless-mocha-plugin';
import { stickerPayload, stickerItem } from './testData';
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('stickerUpdate', '/handler.js', 'update');

const updateId = stickerItem.id;
const updatePayload = {
  ...stickerPayload,
  name: 'i am a sticker',
};

describe('stickerUpdate', () => {

  let existingStickers = [updateId];

  before(() => {

    AWSMock.mock('DynamoDB.DocumentClient', 'get', (params, callback) => {

      let returnValue = null;
      if(existingStickers.includes(params.Key.id)) returnValue = {
        ...stickerItem,
        id: params.Key.id
      };
      callback(null, { Item: returnValue });

    });

    AWSMock.mock('DynamoDB.DocumentClient', 'update', (params, callback) => {

      if(params.Key.id && existingStickers.includes(params.Key.id)) {

        callback(null, 'successfully updated item in database');

      }
      else callback('item not found in database');

    });

  });

  after(() => {

    AWSMock.restore('DynamoDB.DocumentClient');

  });

  it('return 400 for trying to update a sticker with no id', async () => {

    const response = await wrapped.run({
      body: JSON.stringify(updatePayload)
    });
    expect(response.statusCode).to.be.equal(400);

  });

  it('return 404 for trying to update a sticker that doesn\'t exist', async () => {

    const unknownId = 'unknownid';

    const response = await wrapped.run({
      pathParameters: { id: unknownId },
      body: JSON.stringify(updatePayload)
    });
    expect(response.statusCode).to.be.equal(404);

  });

  it('return 406 for trying to update a sticker with invalid name', async () => {

    const invalidPayload = {
      ...updatePayload,
      name: 123456789
    };

    const response = await wrapped.run({
      pathParameters: { id: updateId },
      body: JSON.stringify(invalidPayload)
    });
    expect(response.statusCode).to.be.equal(406);

  });

  it('return 406 for trying to update a sticker with invalid name', async () => {

    const invalidPayload = {
      ...updatePayload,
      name: 123456789
    };

    const response = await wrapped.run({
      pathParameters: { id: updateId },
      body: JSON.stringify(invalidPayload)
    });
    expect(response.statusCode).to.be.equal(406);

  });

  it('return 200 for successfully updating a sticker', async () => {

    const response = await wrapped.run({
      pathParameters: { id: updateId },
      body: JSON.stringify(updatePayload)
    });
    expect(response.statusCode).to.be.equal(200);

  });

});
