service: biztechApi-invites
tenant: ianmh
app: biztechapp

plugins:
  - serverless-domain-manager
  - serverless-bundle
  - serverless-prune-plugin
  - serverless-mocha-plugin

provider:
  name: aws
  stage: ${file(../../serverless.common.yml):provider.stage}
  runtime: ${file(../../serverless.common.yml):provider.runtime}
  region: ${file(../../serverless.common.yml):provider.region}
  cfLogs: true
  environment:
    SENDGRID_KEY: ${param:SENDGRID_KEY}
    ENVIRONMENT: ${file(../../config.${self:provider.stage}.json):ENVIRONMENT}

  apiGateway:
    restApiId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/inviteCodes${file(./config.${self:provider.stage}.json):ENVIRONMENT}"

custom: ${file(../../serverless.common.yml):custom}

functions:
  inviteCreate:
    handler: handler.invite
    events:
      - http:
          path: inviteCodes
          method: post
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp
