service: biztechApi-prizes
tenant: ianmh
app: biztechapp

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-bundle
  - serverless-prune-plugin

provider:
  name: aws
  stage: ${file(../../serverless.common.yml):provider.stage}
  runtime: ${file(../../serverless.common.yml):provider.runtime}
  region: ${file(../../serverless.common.yml):provider.region}
  cfLogs: true
  environment:
    ENVIRONMENT: ${file(../../config.${self:provider.stage}.json):ENVIRONMENT}
  
  apiGateway:
    restApiId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechPrizes${self:provider.environment.ENVIRONMENT}"


custom: ${file(../../serverless.common.yml):custom}

functions:
  prizeGetAll:
    handler: handler.getAll
    events:
      - http:
          path: prizes/
          method: get
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp
  prizeCreate:
    handler: handler.create
    events:
      - http:
          path: prizes/
          method: post
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp
  prizeUpdate:
    handler: handler.update
    events:
      - http:
          path: prizes/{id}
          method: patch
          request:
            path:
              id: true
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp
  prizeDelete:
    handler: handler.del
    events:
      - http:
          path: prizes/{id}
          method: delete
          request:
            path:
              id: true
          cors: true
          authorizer:
            name: ${self:service}-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp