export const CURRENT_EVENT = "blueprint;2025";

export const ATTENDEE = "NFC_ATTENDEE";
export const EXEC = "NFC_EXEC"; // subject to change
export const PARTNER = "NFC_PARTNER";

export const QUEST_CONNECT_ONE = "QUEST_CONNECT_ONE";
export const QUEST_SNACK = "QUEST_SNACK";
export const QUEST_BOOTH_STARTUP = "QUEST_STARTUP";
export const QUEST_BIGTECH = "QUEST_BIGTECH";
export const QUEST_PHOTOBOOTH = "QUEST_PHOTOBOOTH";
export const QUEST_CONNECT_FOUR = "QUEST_CONNECT_FOUR";
export const QUEST_BT_BOOTH_H = "QUEST_BT_BOOTH_H";
export const QUEST_CONNECT_TEN_H = "QUEST_CONNECT_TEN_H";
export const QUEST_CONNECT_EXEC_H = "QUEST_CONNECT_EXEC_H";

export const QUESTS = [
  [QUEST_CONNECT_ONE, 1],
  [QUEST_CONNECT_FOUR, 4],
  [QUEST_CONNECT_TEN_H, 10],
  [QUEST_CONNECT_EXEC_H, 1],
  [QUEST_BT_BOOTH_H, 1],
  [QUEST_SNACK, 1],
  [QUEST_BOOTH_STARTUP, 1],
  [QUEST_BIGTECH, 1],
  [QUEST_PHOTOBOOTH, 1]
];
