service: biztechApi-payments
tenant: ianmh
app: biztechapp

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-domain-manager
  - serverless-bundle
  - serverless-prune-plugin
  - serverless-mocha-plugin

provider:
  name: aws
  stage: ${file(../../serverless.common.yml):provider.stage}
  runtime: ${file(../../serverless.common.yml):provider.runtime}
  region: ${file(../../serverless.common.yml):provider.region}
  cfLogs: true
  environment:
    ENVIRONMENT: ${file(../../config.${self:provider.stage}.json):ENVIRONMENT}
    STRIPE_DEV_CANCEL: ${env:STRIPE_DEV_CANCEL, 'default'}
    STRIPE_DEV_ENDPOINT: ${env:STRIPE_DEV_ENDPOINT, 'default'}
    STRIPE_PROD_CANCEL: ${env:STRIPE_PROD_CANCEL, 'default'}
    STRIPE_PROD_ENDPOINT: ${env:STRIPE_PROD_ENDPOINT, 'default'}
    STRIPE_PROD_KEY: ${env:STRIPE_PROD_KEY, 'default'}
    STRIPE_DEV_KEY: ${env:STRIPE_DEV_KEY, 'default'}
    NODE_ENV: ${env:NODE_ENV}
    SNS_TOPIC_ARN: arn:aws:sns:us-west-2:432714361962:slackbot
  apiGateway:
    restApiId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechMembers2022${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechMembers2023${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechMembers2024${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechMembers2025${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechMembers2026${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechUsers${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:SignUp
      Resource:
        - "arn:aws:cognito-idp:us-west-2:432714361962:userpool/us-west-2_w0R176hhp"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechRegistrations${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechEvents${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:TransactWriteItems
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechProfiles${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - ${self:provider.environment.SNS_TOPIC_ARN}
    - Effect: Allow
      Action:
        - ses:SendRawEmail
      Resource:
        - "arn:aws:ses:us-west-2:432714361962:identity/dev@ubcbiztech.com"
        - "arn:aws:ses:us-west-2:432714361962:configuration-set/my-first-configuration-set"

custom: ${file(../../serverless.common.yml):custom}

functions:
  payment:
    handler: handler.payment
    events:
      - http:
          path: payments
          method: post
          cors: true
  paymentWebhook:
    handler: handler.webhook
    events:
      - http:
          path: payments/webhook
          method: post
          cors: true
  paymentCancelWebhook:
    handler: handler.cancel
    events:
      - http:
          path: payments/cancel
          method: post
          cors: true
