name: Deploy on merge
'on':
  push:
    branches: [ dev, master ]

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Use Node.js
     uses: actions/setup-node@v4
     with:
       node-version: '18.x'

   - name: Cache node modules
     uses: actions/cache@v2
     env:
       cache-name: cache-node-modules
     with:
       path: ~/.npm
       key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
         ${{ runner.os }}-build-${{ env.cache-name }}-
         ${{ runner.os }}-build-
         ${{ runner.os }}-

   - name: Install dependencies and Serverless CLI
     run: |
       npm ci
       npm install serverless

   - name: 'Deploy Dev'
     if: github.ref == 'refs/heads/dev'
     env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      STRIPE_DEV_CANCEL: ${{ secrets.STRIPE_DEV_CANCEL }}
      STRIPE_DEV_ENDPOINT: ${{ secrets.STRIPE_DEV_ENDPOINT }}
      STRIPE_PROD_CANCEL: ${{ secrets.STRIPE_PROD_CANCEL }}
      STRIPE_PROD_ENDPOINT: ${{ secrets.STRIPE_PROD_ENDPOINT }}
      STRIPE_PROD_KEY: ${{ secrets.STRIPE_PROD_KEY }}
      STRIPE_DEV_KEY: ${{ secrets.STRIPE_DEV_KEY }}
     run: |
      cd services
      for DIR in *; do
       (cd $DIR && npx serverless deploy --conceal && cd ..) & done; wait

   - name: 'Deploy Prod'
     if: github.ref == 'refs/heads/master'
     env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      STRIPE_DEV_CANCEL: ${{ secrets.STRIPE_DEV_CANCEL }}
      STRIPE_DEV_ENDPOINT: ${{ secrets.STRIPE_DEV_ENDPOINT }}
      STRIPE_PROD_CANCEL: ${{ secrets.STRIPE_PROD_CANCEL }}
      STRIPE_PROD_ENDPOINT: ${{ secrets.STRIPE_PROD_ENDPOINT }}
      STRIPE_PROD_KEY: ${{ secrets.STRIPE_PROD_KEY }}
      STRIPE_DEV_KEY: ${{ secrets.STRIPE_DEV_KEY }}
     run: |
      cd services
      for DIR in *; do
        (cd $DIR && npx serverless deploy --stage prod --conceal && cd ..) & done; wait