name: Deploy Prod

on:
  release:
    types: [published]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.7
        uses: actions/setup-node@v4
        with:
          node-version: "20.7"

      # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            */node_modules
            services/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Serverless CLI and dependencies
        run: |
          sudo npm i -g serverless@3 --legacy-peer-deps
          npm ci --legacy-peer-deps
          # Install dependencies for all services
          cd services
          for DIR in *; do
            if [ -f "$DIR/package.json" ]; then
              echo "Installing dependencies for $DIR"
              cd "$DIR"
              npm ci --legacy-peer-deps
              cd ..
            fi
          done

      - name: "Deploy and test Production"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_PROJECT_ACCESS_KEY: ${{ secrets.GH_PROJECT_ACCESS_KEY }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          STRIPE_DEV_CANCEL: ${{ secrets.STRIPE_DEV_CANCEL }}
          STRIPE_DEV_ENDPOINT: ${{ secrets.STRIPE_DEV_ENDPOINT }}
          STRIPE_PROD_CANCEL: ${{ secrets.STRIPE_PROD_CANCEL }}
          STRIPE_PROD_ENDPOINT: ${{ secrets.STRIPE_PROD_ENDPOINT }}
          STRIPE_PROD_KEY: ${{ secrets.STRIPE_PROD_KEY}}
          STRIPE_DEV_KEY: ${{ secrets.STRIPE_DEV_KEY}}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        # TODO: deploy all to production
        run: |
          cd services
          for DIR in *; do (cd $DIR && npx sls deploy --stage prod --conceal && cd ..) & done; wait
          echo "Finished deployment in prod"
